<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class ReportOtherDebtSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $debts = [
            ['subscription_report_id' => 1, 'entity' => 'Telefónica', 'currency' => 'PEN', 'amount' => 2500.00, 'expiration_days' => 0],
            ['subscription_report_id' => 2, 'entity' => 'Claro', 'currency' => 'PEN', 'amount' => 1800.00, 'expiration_days' => 15],
            ['subscription_report_id' => 2, 'entity' => 'Sedapal', 'currency' => 'PEN', 'amount' => 850.00, 'expiration_days' => 0],
            ['subscription_report_id' => 3, 'entity' => 'Luz del Sur', 'currency' => 'PEN', 'amount' => 1200.00, 'expiration_days' => 28],
            ['subscription_report_id' => 4, 'entity' => 'Entel', 'currency' => 'PEN', 'amount' => 3500.00, 'expiration_days' => 45],
            ['subscription_report_id' => 4, 'entity' => 'Caja Arequipa', 'currency' => 'PEN', 'amount' => 8000.00, 'expiration_days' => 0],
            ['subscription_report_id' => 5, 'entity' => 'Financiera Confianza', 'currency' => 'PEN', 'amount' => 5500.00, 'expiration_days' => 12],
            ['subscription_report_id' => 6, 'entity' => 'Telefónica', 'currency' => 'PEN', 'amount' => 1500.00, 'expiration_days' => 0],
            ['subscription_report_id' => 7, 'entity' => 'Claro', 'currency' => 'PEN', 'amount' => 2200.00, 'expiration_days' => 35],
            ['subscription_report_id' => 8, 'entity' => 'Caja Huancayo', 'currency' => 'PEN', 'amount' => 12000.00, 'expiration_days' => 60],
            ['subscription_report_id' => 8, 'entity' => 'Sedapal', 'currency' => 'PEN', 'amount' => 650.00, 'expiration_days' => 0],
            ['subscription_report_id' => 9, 'entity' => 'Luz del Sur', 'currency' => 'PEN', 'amount' => 980.00, 'expiration_days' => 0],
            ['subscription_report_id' => 10, 'entity' => 'Entel', 'currency' => 'PEN', 'amount' => 1800.00, 'expiration_days' => 22],
            ['subscription_report_id' => 11, 'entity' => 'Caja Piura', 'currency' => 'PEN', 'amount' => 15000.00, 'expiration_days' => 0],
            ['subscription_report_id' => 12, 'entity' => 'Financiera Credinka', 'currency' => 'PEN', 'amount' => 7500.00, 'expiration_days' => 40],
            ['subscription_report_id' => 13, 'entity' => 'Telefónica', 'currency' => 'PEN', 'amount' => 2100.00, 'expiration_days' => 0],
            ['subscription_report_id' => 13, 'entity' => 'Claro', 'currency' => 'PEN', 'amount' => 1650.00, 'expiration_days' => 18],
            ['subscription_report_id' => 14, 'entity' => 'Caja Sullana', 'currency' => 'PEN', 'amount' => 9500.00, 'expiration_days' => 75],
            ['subscription_report_id' => 15, 'entity' => 'Sedapal', 'currency' => 'PEN', 'amount' => 720.00, 'expiration_days' => 0],
            ['subscription_report_id' => 16, 'entity' => 'Luz del Sur', 'currency' => 'PEN', 'amount' => 1100.00, 'expiration_days' => 0],
            ['subscription_report_id' => 17, 'entity' => 'Entel', 'currency' => 'PEN', 'amount' => 2800.00, 'expiration_days' => 30],
            ['subscription_report_id' => 18, 'entity' => 'Caja Cusco', 'currency' => 'PEN', 'amount' => 11000.00, 'expiration_days' => 0],
            ['subscription_report_id' => 18, 'entity' => 'Financiera Oh', 'currency' => 'PEN', 'amount' => 4500.00, 'expiration_days' => 25],
            ['subscription_report_id' => 19, 'entity' => 'Telefónica', 'currency' => 'PEN', 'amount' => 1950.00, 'expiration_days' => 55],
            ['subscription_report_id' => 20, 'entity' => 'Claro', 'currency' => 'PEN', 'amount' => 2400.00, 'expiration_days' => 0],
            ['subscription_report_id' => 21, 'entity' => 'Caja Trujillo', 'currency' => 'PEN', 'amount' => 8500.00, 'expiration_days' => 42],
            ['subscription_report_id' => 22, 'entity' => 'Sedapal', 'currency' => 'PEN', 'amount' => 580.00, 'expiration_days' => 0],
            ['subscription_report_id' => 22, 'entity' => 'Luz del Sur', 'currency' => 'PEN', 'amount' => 890.00, 'expiration_days' => 0],
            ['subscription_report_id' => 23, 'entity' => 'Entel', 'currency' => 'PEN', 'amount' => 3200.00, 'expiration_days' => 0],
            ['subscription_report_id' => 24, 'entity' => 'Caja Ica', 'currency' => 'PEN', 'amount' => 6500.00, 'expiration_days' => 90],
            ['subscription_report_id' => 25, 'entity' => 'Financiera Proempresa', 'currency' => 'PEN', 'amount' => 9000.00, 'expiration_days' => 0],
            ['subscription_report_id' => 26, 'entity' => 'Telefónica', 'currency' => 'PEN', 'amount' => 1750.00, 'expiration_days' => 20],
            ['subscription_report_id' => 27, 'entity' => 'Claro', 'currency' => 'PEN', 'amount' => 2050.00, 'expiration_days' => 0],
            ['subscription_report_id' => 28, 'entity' => 'Caja Tacna', 'currency' => 'PEN', 'amount' => 7000.00, 'expiration_days' => 48],
            ['subscription_report_id' => 28, 'entity' => 'Sedapal', 'currency' => 'PEN', 'amount' => 920.00, 'expiration_days' => 0],
            ['subscription_report_id' => 29, 'entity' => 'Luz del Sur', 'currency' => 'PEN', 'amount' => 1350.00, 'expiration_days' => 0],
            ['subscription_report_id' => 30, 'entity' => 'Entel', 'currency' => 'PEN', 'amount' => 2650.00, 'expiration_days' => 65],
            ['subscription_report_id' => 31, 'entity' => 'Caja Maynas', 'currency' => 'PEN', 'amount' => 10500.00, 'expiration_days' => 0],
            ['subscription_report_id' => 32, 'entity' => 'Financiera Compartamos', 'currency' => 'PEN', 'amount' => 5000.00, 'expiration_days' => 15],
            ['subscription_report_id' => 33, 'entity' => 'Telefónica', 'currency' => 'PEN', 'amount' => 2300.00, 'expiration_days' => 38],
            ['subscription_report_id' => 34, 'entity' => 'Claro', 'currency' => 'PEN', 'amount' => 1900.00, 'expiration_days' => 0],
            ['subscription_report_id' => 34, 'entity' => 'Caja Metropolitana', 'currency' => 'PEN', 'amount' => 13500.00, 'expiration_days' => 0],
            ['subscription_report_id' => 35, 'entity' => 'Sedapal', 'currency' => 'PEN', 'amount' => 780.00, 'expiration_days' => 0],
            ['subscription_report_id' => 36, 'entity' => 'Luz del Sur', 'currency' => 'PEN', 'amount' => 1050.00, 'expiration_days' => 25],
            ['subscription_report_id' => 37, 'entity' => 'Entel', 'currency' => 'PEN', 'amount' => 3800.00, 'expiration_days' => 0],
            ['subscription_report_id' => 38, 'entity' => 'Caja Arequipa', 'currency' => 'PEN', 'amount' => 9200.00, 'expiration_days' => 52],
            ['subscription_report_id' => 39, 'entity' => 'Financiera Confianza', 'currency' => 'PEN', 'amount' => 6800.00, 'expiration_days' => 0],
            ['subscription_report_id' => 39, 'entity' => 'Telefónica', 'currency' => 'PEN', 'amount' => 1600.00, 'expiration_days' => 0],
            ['subscription_report_id' => 40, 'entity' => 'Claro', 'currency' => 'PEN', 'amount' => 2150.00, 'expiration_days' => 0],
            ['subscription_report_id' => 41, 'entity' => 'Caja Huancayo', 'currency' => 'PEN', 'amount' => 14000.00, 'expiration_days' => 78],
            ['subscription_report_id' => 42, 'entity' => 'Sedapal', 'currency' => 'PEN', 'amount' => 690.00, 'expiration_days' => 0],
            ['subscription_report_id' => 43, 'entity' => 'Luz del Sur', 'currency' => 'PEN', 'amount' => 1280.00, 'expiration_days' => 0],
            ['subscription_report_id' => 44, 'entity' => 'Entel', 'currency' => 'PEN', 'amount' => 2950.00, 'expiration_days' => 22],
            ['subscription_report_id' => 45, 'entity' => 'Caja Piura', 'currency' => 'PEN', 'amount' => 8800.00, 'expiration_days' => 48],
            ['subscription_report_id' => 45, 'entity' => 'Financiera Credinka', 'currency' => 'PEN', 'amount' => 4200.00, 'expiration_days' => 0],
            ['subscription_report_id' => 46, 'entity' => 'Telefónica', 'currency' => 'PEN', 'amount' => 2000.00, 'expiration_days' => 0],
            ['subscription_report_id' => 47, 'entity' => 'Claro', 'currency' => 'PEN', 'amount' => 1700.00, 'expiration_days' => 88],
            ['subscription_report_id' => 48, 'entity' => 'Caja Sullana', 'currency' => 'PEN', 'amount' => 11500.00, 'expiration_days' => 0],
            ['subscription_report_id' => 49, 'entity' => 'Sedapal', 'currency' => 'PEN', 'amount' => 820.00, 'expiration_days' => 0],
            ['subscription_report_id' => 49, 'entity' => 'Luz del Sur', 'currency' => 'PEN', 'amount' => 1150.00, 'expiration_days' => 28],
            ['subscription_report_id' => 50, 'entity' => 'Entel', 'currency' => 'PEN', 'amount' => 3100.00, 'expiration_days' => 42],
            ['subscription_report_id' => 51, 'entity' => 'Caja Cusco', 'currency' => 'PEN', 'amount' => 7200.00, 'expiration_days' => 0],
            ['subscription_report_id' => 52, 'entity' => 'Financiera Oh', 'currency' => 'PEN', 'amount' => 5800.00, 'expiration_days' => 18],
            ['subscription_report_id' => 53, 'entity' => 'Telefónica', 'currency' => 'PEN', 'amount' => 2450.00, 'expiration_days' => 95],
            ['subscription_report_id' => 54, 'entity' => 'Claro', 'currency' => 'PEN', 'amount' => 1850.00, 'expiration_days' => 0],
            ['subscription_report_id' => 55, 'entity' => 'Caja Trujillo', 'currency' => 'PEN', 'amount' => 10000.00, 'expiration_days' => 55],
            ['subscription_report_id' => 55, 'entity' => 'Sedapal', 'currency' => 'PEN', 'amount' => 950.00, 'expiration_days' => 25],
            ['subscription_report_id' => 56, 'entity' => 'Luz del Sur', 'currency' => 'PEN', 'amount' => 1000.00, 'expiration_days' => 0],
            ['subscription_report_id' => 57, 'entity' => 'Entel', 'currency' => 'PEN', 'amount' => 2700.00, 'expiration_days' => 30],
            ['subscription_report_id' => 58, 'entity' => 'Caja Ica', 'currency' => 'PEN', 'amount' => 8200.00, 'expiration_days' => 0],
            ['subscription_report_id' => 59, 'entity' => 'Financiera Proempresa', 'currency' => 'PEN', 'amount' => 6200.00, 'expiration_days' => 50],
            ['subscription_report_id' => 60, 'entity' => 'Telefónica', 'currency' => 'PEN', 'amount' => 1550.00, 'expiration_days' => 82],
            ['subscription_report_id' => 61, 'entity' => 'Claro', 'currency' => 'PEN', 'amount' => 2250.00, 'expiration_days' => 22],
            ['subscription_report_id' => 62, 'entity' => 'Caja Tacna', 'currency' => 'PEN', 'amount' => 9800.00, 'expiration_days' => 0],
            ['subscription_report_id' => 62, 'entity' => 'Sedapal', 'currency' => 'PEN', 'amount' => 750.00, 'expiration_days' => 0],
            ['subscription_report_id' => 63, 'entity' => 'Luz del Sur', 'currency' => 'PEN', 'amount' => 1180.00, 'expiration_days' => 45],
            ['subscription_report_id' => 64, 'entity' => 'Entel', 'currency' => 'PEN', 'amount' => 3400.00, 'expiration_days' => 28],
            ['subscription_report_id' => 65, 'entity' => 'Caja Maynas', 'currency' => 'PEN', 'amount' => 7800.00, 'expiration_days' => 0],
            ['subscription_report_id' => 66, 'entity' => 'Financiera Compartamos', 'currency' => 'PEN', 'amount' => 4800.00, 'expiration_days' => 90],
            ['subscription_report_id' => 67, 'entity' => 'Telefónica', 'currency' => 'PEN', 'amount' => 2100.00, 'expiration_days' => 18],
            ['subscription_report_id' => 68, 'entity' => 'Claro', 'currency' => 'PEN', 'amount' => 1950.00, 'expiration_days' => 40],
            ['subscription_report_id' => 68, 'entity' => 'Caja Metropolitana', 'currency' => 'PEN', 'amount' => 12500.00, 'expiration_days' => 0],
            ['subscription_report_id' => 69, 'entity' => 'Sedapal', 'currency' => 'PEN', 'amount' => 680.00, 'expiration_days' => 0],
            ['subscription_report_id' => 70, 'entity' => 'Luz del Sur', 'currency' => 'PEN', 'amount' => 1320.00, 'expiration_days' => 25],
            ['subscription_report_id' => 71, 'entity' => 'Entel', 'currency' => 'PEN', 'amount' => 2850.00, 'expiration_days' => 78],
            ['subscription_report_id' => 72, 'entity' => 'Caja Arequipa', 'currency' => 'PEN', 'amount' => 10200.00, 'expiration_days' => 0],
            ['subscription_report_id' => 73, 'entity' => 'Financiera Confianza', 'currency' => 'PEN', 'amount' => 5200.00, 'expiration_days' => 52],
            ['subscription_report_id' => 74, 'entity' => 'Telefónica', 'currency' => 'PEN', 'amount' => 1800.00, 'expiration_days' => 20],
            ['subscription_report_id' => 74, 'entity' => 'Claro', 'currency' => 'PEN', 'amount' => 2350.00, 'expiration_days' => 0],
            ['subscription_report_id' => 75, 'entity' => 'Caja Huancayo', 'currency' => 'PEN', 'amount' => 8500.00, 'expiration_days' => 0],
            ['subscription_report_id' => 76, 'entity' => 'Sedapal', 'currency' => 'PEN', 'amount' => 880.00, 'expiration_days' => 48],
            ['subscription_report_id' => 77, 'entity' => 'Luz del Sur', 'currency' => 'PEN', 'amount' => 1080.00, 'expiration_days' => 15],
            ['subscription_report_id' => 78, 'entity' => 'Entel', 'currency' => 'PEN', 'amount' => 3600.00, 'expiration_days' => 85],
            ['subscription_report_id' => 79, 'entity' => 'Caja Piura', 'currency' => 'PEN', 'amount' => 9500.00, 'expiration_days' => 0],
            ['subscription_report_id' => 80, 'entity' => 'Financiera Credinka', 'currency' => 'PEN', 'amount' => 6500.00, 'expiration_days' => 28],
            ['subscription_report_id' => 80, 'entity' => 'Telefónica', 'currency' => 'PEN', 'amount' => 2200.00, 'expiration_days' => 0],
            ['subscription_report_id' => 81, 'entity' => 'Claro', 'currency' => 'PEN', 'amount' => 1750.00, 'expiration_days' => 42],
            ['subscription_report_id' => 82, 'entity' => 'Caja Sullana', 'currency' => 'PEN', 'amount' => 11800.00, 'expiration_days' => 0],
            ['subscription_report_id' => 83, 'entity' => 'Sedapal', 'currency' => 'PEN', 'amount' => 720.00, 'expiration_days' => 92],
            ['subscription_report_id' => 84, 'entity' => 'Luz del Sur', 'currency' => 'PEN', 'amount' => 1250.00, 'expiration_days' => 22],
            ['subscription_report_id' => 85, 'entity' => 'Entel', 'currency' => 'PEN', 'amount' => 3000.00, 'expiration_days' => 0],
            ['subscription_report_id' => 86, 'entity' => 'Caja Cusco', 'currency' => 'PEN', 'amount' => 7500.00, 'expiration_days' => 55],
            ['subscription_report_id' => 86, 'entity' => 'Financiera Oh', 'currency' => 'PEN', 'amount' => 4000.00, 'expiration_days' => 0],
            ['subscription_report_id' => 87, 'entity' => 'Telefónica', 'currency' => 'PEN', 'amount' => 1650.00, 'expiration_days' => 25],
            ['subscription_report_id' => 88, 'entity' => 'Claro', 'currency' => 'PEN', 'amount' => 2500.00, 'expiration_days' => 0],
            ['subscription_report_id' => 89, 'entity' => 'Caja Trujillo', 'currency' => 'PEN', 'amount' => 10800.00, 'expiration_days' => 80],
            ['subscription_report_id' => 90, 'entity' => 'Sedapal', 'currency' => 'PEN', 'amount' => 850.00, 'expiration_days' => 30],
            ['subscription_report_id' => 91, 'entity' => 'Luz del Sur', 'currency' => 'PEN', 'amount' => 1150.00, 'expiration_days' => 45],
            ['subscription_report_id' => 92, 'entity' => 'Entel', 'currency' => 'PEN', 'amount' => 2900.00, 'expiration_days' => 0],
            ['subscription_report_id' => 92, 'entity' => 'Caja Ica', 'currency' => 'PEN', 'amount' => 8000.00, 'expiration_days' => 0],
            ['subscription_report_id' => 93, 'entity' => 'Financiera Proempresa', 'currency' => 'PEN', 'amount' => 5500.00, 'expiration_days' => 18],
            ['subscription_report_id' => 94, 'entity' => 'Telefónica', 'currency' => 'PEN', 'amount' => 2050.00, 'expiration_days' => 88],
            ['subscription_report_id' => 95, 'entity' => 'Claro', 'currency' => 'PEN', 'amount' => 1900.00, 'expiration_days' => 0],
            ['subscription_report_id' => 96, 'entity' => 'Caja Tacna', 'currency' => 'PEN', 'amount' => 9200.00, 'expiration_days' => 50],
            ['subscription_report_id' => 97, 'entity' => 'Sedapal', 'currency' => 'PEN', 'amount' => 780.00, 'expiration_days' => 22],
            ['subscription_report_id' => 97, 'entity' => 'Luz del Sur', 'currency' => 'PEN', 'amount' => 1100.00, 'expiration_days' => 0],
            ['subscription_report_id' => 98, 'entity' => 'Entel', 'currency' => 'PEN', 'amount' => 3300.00, 'expiration_days' => 0],
            ['subscription_report_id' => 99, 'entity' => 'Caja Maynas', 'currency' => 'PEN', 'amount' => 7000.00, 'expiration_days' => 48],
            ['subscription_report_id' => 100, 'entity' => 'Financiera Compartamos', 'currency' => 'PEN', 'amount' => 4500.00, 'expiration_days' => 28],
        ];

        DB::table('report_other_debts')->insert($debts);
    }
}
