<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class ReportLoanSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $loans = [
            ['subscription_report_id' => 1, 'bank' => 'BCP', 'status' => 'NOR', 'currency' => 'PEN', 'amount' => 15000.00, 'expiration_days' => 0],
            ['subscription_report_id' => 1, 'bank' => 'Interbank', 'status' => 'CPP', 'currency' => 'PEN', 'amount' => 8500.50, 'expiration_days' => 15],
            ['subscription_report_id' => 2, 'bank' => 'BBVA', 'status' => 'NOR', 'currency' => 'PEN', 'amount' => 25000.00, 'expiration_days' => 0],
            ['subscription_report_id' => 3, 'bank' => 'Scotiabank', 'status' => 'DEF', 'currency' => 'PEN', 'amount' => 12000.00, 'expiration_days' => 45],
            ['subscription_report_id' => 3, 'bank' => 'BCP', 'status' => 'NOR', 'currency' => 'PEN', 'amount' => 5000.00, 'expiration_days' => 0],
            ['subscription_report_id' => 3, 'bank' => 'Interbank', 'status' => 'CPP', 'currency' => 'PEN', 'amount' => 18000.00, 'expiration_days' => 22],
            ['subscription_report_id' => 4, 'bank' => 'BBVA', 'status' => 'PER', 'currency' => 'PEN', 'amount' => 35000.00, 'expiration_days' => 90],
            ['subscription_report_id' => 5, 'bank' => 'BanBif', 'status' => 'NOR', 'currency' => 'PEN', 'amount' => 7500.00, 'expiration_days' => 0],
            ['subscription_report_id' => 5, 'bank' => 'Scotiabank', 'status' => 'NOR', 'currency' => 'PEN', 'amount' => 9800.00, 'expiration_days' => 0],
            ['subscription_report_id' => 6, 'bank' => 'BCP', 'status' => 'CPP', 'currency' => 'PEN', 'amount' => 22000.00, 'expiration_days' => 28],
            ['subscription_report_id' => 7, 'bank' => 'Interbank', 'status' => 'NOR', 'currency' => 'PEN', 'amount' => 11000.00, 'expiration_days' => 0],
            ['subscription_report_id' => 7, 'bank' => 'BBVA', 'status' => 'DEF', 'currency' => 'PEN', 'amount' => 45000.00, 'expiration_days' => 55],
            ['subscription_report_id' => 7, 'bank' => 'Scotiabank', 'status' => 'NOR', 'currency' => 'PEN', 'amount' => 6000.00, 'expiration_days' => 0],
            ['subscription_report_id' => 8, 'bank' => 'BanBif', 'status' => 'PER', 'currency' => 'PEN', 'amount' => 28000.00, 'expiration_days' => 75],
            ['subscription_report_id' => 8, 'bank' => 'BCP', 'status' => 'CPP', 'currency' => 'PEN', 'amount' => 15500.00, 'expiration_days' => 18],
            ['subscription_report_id' => 10, 'bank' => 'Interbank', 'status' => 'NOR', 'currency' => 'PEN', 'amount' => 8000.00, 'expiration_days' => 0],
            ['subscription_report_id' => 11, 'bank' => 'BBVA', 'status' => 'NOR', 'currency' => 'PEN', 'amount' => 19000.00, 'expiration_days' => 0],
            ['subscription_report_id' => 11, 'bank' => 'Scotiabank', 'status' => 'CPP', 'currency' => 'PEN', 'amount' => 32000.00, 'expiration_days' => 25],
            ['subscription_report_id' => 12, 'bank' => 'BCP', 'status' => 'DEF', 'currency' => 'PEN', 'amount' => 14000.00, 'expiration_days' => 40],
            ['subscription_report_id' => 13, 'bank' => 'BanBif', 'status' => 'NOR', 'currency' => 'PEN', 'amount' => 5500.00, 'expiration_days' => 0],
            ['subscription_report_id' => 13, 'bank' => 'Interbank', 'status' => 'NOR', 'currency' => 'PEN', 'amount' => 7200.00, 'expiration_days' => 0],
            ['subscription_report_id' => 13, 'bank' => 'BBVA', 'status' => 'CPP', 'currency' => 'PEN', 'amount' => 21000.00, 'expiration_days' => 12],
            ['subscription_report_id' => 14, 'bank' => 'Scotiabank', 'status' => 'PER', 'currency' => 'PEN', 'amount' => 48000.00, 'expiration_days' => 95],
            ['subscription_report_id' => 15, 'bank' => 'BCP', 'status' => 'NOR', 'currency' => 'PEN', 'amount' => 10000.00, 'expiration_days' => 0],
            ['subscription_report_id' => 16, 'bank' => 'Interbank', 'status' => 'DEF', 'currency' => 'PEN', 'amount' => 27000.00, 'expiration_days' => 50],
            ['subscription_report_id' => 16, 'bank' => 'BBVA', 'status' => 'NOR', 'currency' => 'PEN', 'amount' => 8900.00, 'expiration_days' => 0],
            ['subscription_report_id' => 17, 'bank' => 'BanBif', 'status' => 'CPP', 'currency' => 'PEN', 'amount' => 16000.00, 'expiration_days' => 20],
            ['subscription_report_id' => 18, 'bank' => 'Scotiabank', 'status' => 'NOR', 'currency' => 'PEN', 'amount' => 12500.00, 'expiration_days' => 0],
            ['subscription_report_id' => 18, 'bank' => 'BCP', 'status' => 'NOR', 'currency' => 'PEN', 'amount' => 9000.00, 'expiration_days' => 0],
            ['subscription_report_id' => 19, 'bank' => 'Interbank', 'status' => 'PER', 'currency' => 'PEN', 'amount' => 38000.00, 'expiration_days' => 80],
            ['subscription_report_id' => 20, 'bank' => 'BBVA', 'status' => 'NOR', 'currency' => 'PEN', 'amount' => 6500.00, 'expiration_days' => 0],
            ['subscription_report_id' => 20, 'bank' => 'BanBif', 'status' => 'CPP', 'currency' => 'PEN', 'amount' => 23000.00, 'expiration_days' => 30],
            ['subscription_report_id' => 21, 'bank' => 'Scotiabank', 'status' => 'DEF', 'currency' => 'PEN', 'amount' => 17000.00, 'expiration_days' => 42],
            ['subscription_report_id' => 22, 'bank' => 'BCP', 'status' => 'NOR', 'currency' => 'PEN', 'amount' => 11500.00, 'expiration_days' => 0],
            ['subscription_report_id' => 22, 'bank' => 'Interbank', 'status' => 'NOR', 'currency' => 'PEN', 'amount' => 7800.00, 'expiration_days' => 0],
            ['subscription_report_id' => 22, 'bank' => 'BBVA', 'status' => 'CPP', 'currency' => 'PEN', 'amount' => 29000.00, 'expiration_days' => 15],
            ['subscription_report_id' => 23, 'bank' => 'BanBif', 'status' => 'NOR', 'currency' => 'PEN', 'amount' => 4500.00, 'expiration_days' => 0],
            ['subscription_report_id' => 24, 'bank' => 'Scotiabank', 'status' => 'PER', 'currency' => 'PEN', 'amount' => 42000.00, 'expiration_days' => 100],
            ['subscription_report_id' => 24, 'bank' => 'BCP', 'status' => 'DEF', 'currency' => 'PEN', 'amount' => 18500.00, 'expiration_days' => 48],
            ['subscription_report_id' => 25, 'bank' => 'Interbank', 'status' => 'NOR', 'currency' => 'PEN', 'amount' => 9500.00, 'expiration_days' => 0],
            ['subscription_report_id' => 26, 'bank' => 'BBVA', 'status' => 'CPP', 'currency' => 'PEN', 'amount' => 26000.00, 'expiration_days' => 22],
            ['subscription_report_id' => 27, 'bank' => 'BanBif', 'status' => 'NOR', 'currency' => 'PEN', 'amount' => 8200.00, 'expiration_days' => 0],
            ['subscription_report_id' => 27, 'bank' => 'Scotiabank', 'status' => 'NOR', 'currency' => 'PEN', 'amount' => 13000.00, 'expiration_days' => 0],
            ['subscription_report_id' => 28, 'bank' => 'BCP', 'status' => 'DEF', 'currency' => 'PEN', 'amount' => 31000.00, 'expiration_days' => 55],
            ['subscription_report_id' => 29, 'bank' => 'Interbank', 'status' => 'NOR', 'currency' => 'PEN', 'amount' => 7000.00, 'expiration_days' => 0],
            ['subscription_report_id' => 29, 'bank' => 'BBVA', 'status' => 'CPP', 'currency' => 'PEN', 'amount' => 19500.00, 'expiration_days' => 18],
            ['subscription_report_id' => 30, 'bank' => 'BanBif', 'status' => 'PER', 'currency' => 'PEN', 'amount' => 36000.00, 'expiration_days' => 85],
            ['subscription_report_id' => 31, 'bank' => 'Scotiabank', 'status' => 'NOR', 'currency' => 'PEN', 'amount' => 10500.00, 'expiration_days' => 0],
            ['subscription_report_id' => 32, 'bank' => 'BCP', 'status' => 'NOR', 'currency' => 'PEN', 'amount' => 6800.00, 'expiration_days' => 0],
            ['subscription_report_id' => 32, 'bank' => 'Interbank', 'status' => 'CPP', 'currency' => 'PEN', 'amount' => 24000.00, 'expiration_days' => 28],
            ['subscription_report_id' => 33, 'bank' => 'BBVA', 'status' => 'DEF', 'currency' => 'PEN', 'amount' => 15000.00, 'expiration_days' => 38],
            ['subscription_report_id' => 34, 'bank' => 'BanBif', 'status' => 'NOR', 'currency' => 'PEN', 'amount' => 8800.00, 'expiration_days' => 0],
            ['subscription_report_id' => 34, 'bank' => 'Scotiabank', 'status' => 'NOR', 'currency' => 'PEN', 'amount' => 12200.00, 'expiration_days' => 0],
            ['subscription_report_id' => 35, 'bank' => 'BCP', 'status' => 'PER', 'currency' => 'PEN', 'amount' => 44000.00, 'expiration_days' => 92],
            ['subscription_report_id' => 36, 'bank' => 'Interbank', 'status' => 'CPP', 'currency' => 'PEN', 'amount' => 20000.00, 'expiration_days' => 25],
            ['subscription_report_id' => 37, 'bank' => 'BBVA', 'status' => 'NOR', 'currency' => 'PEN', 'amount' => 9200.00, 'expiration_days' => 0],
            ['subscription_report_id' => 38, 'bank' => 'BanBif', 'status' => 'DEF', 'currency' => 'PEN', 'amount' => 28500.00, 'expiration_days' => 45],
            ['subscription_report_id' => 38, 'bank' => 'Scotiabank', 'status' => 'NOR', 'currency' => 'PEN', 'amount' => 7500.00, 'expiration_days' => 0],
            ['subscription_report_id' => 39, 'bank' => 'BCP', 'status' => 'NOR', 'currency' => 'PEN', 'amount' => 11800.00, 'expiration_days' => 0],
            ['subscription_report_id' => 39, 'bank' => 'Interbank', 'status' => 'CPP', 'currency' => 'PEN', 'amount' => 17500.00, 'expiration_days' => 20],
            ['subscription_report_id' => 40, 'bank' => 'BBVA', 'status' => 'NOR', 'currency' => 'PEN', 'amount' => 6200.00, 'expiration_days' => 0],
            ['subscription_report_id' => 41, 'bank' => 'BanBif', 'status' => 'PER', 'currency' => 'PEN', 'amount' => 39000.00, 'expiration_days' => 78],
            ['subscription_report_id' => 41, 'bank' => 'Scotiabank', 'status' => 'DEF', 'currency' => 'PEN', 'amount' => 22500.00, 'expiration_days' => 52],
            ['subscription_report_id' => 42, 'bank' => 'BCP', 'status' => 'NOR', 'currency' => 'PEN', 'amount' => 8500.00, 'expiration_days' => 0],
            ['subscription_report_id' => 43, 'bank' => 'Interbank', 'status' => 'CPP', 'currency' => 'PEN', 'amount' => 14500.00, 'expiration_days' => 15],
            ['subscription_report_id' => 44, 'bank' => 'BBVA', 'status' => 'NOR', 'currency' => 'PEN', 'amount' => 10800.00, 'expiration_days' => 0],
            ['subscription_report_id' => 44, 'bank' => 'BanBif', 'status' => 'NOR', 'currency' => 'PEN', 'amount' => 7200.00, 'expiration_days' => 0],
            ['subscription_report_id' => 45, 'bank' => 'Scotiabank', 'status' => 'DEF', 'currency' => 'PEN', 'amount' => 33000.00, 'expiration_days' => 48],
            ['subscription_report_id' => 46, 'bank' => 'BCP', 'status' => 'NOR', 'currency' => 'PEN', 'amount' => 5800.00, 'expiration_days' => 0],
            ['subscription_report_id' => 46, 'bank' => 'Interbank', 'status' => 'CPP', 'currency' => 'PEN', 'amount' => 21500.00, 'expiration_days' => 22],
            ['subscription_report_id' => 47, 'bank' => 'BBVA', 'status' => 'PER', 'currency' => 'PEN', 'amount' => 47000.00, 'expiration_days' => 88],
            ['subscription_report_id' => 48, 'bank' => 'BanBif', 'status' => 'NOR', 'currency' => 'PEN', 'amount' => 9800.00, 'expiration_days' => 0],
            ['subscription_report_id' => 49, 'bank' => 'Scotiabank', 'status' => 'NOR', 'currency' => 'PEN', 'amount' => 13500.00, 'expiration_days' => 0],
            ['subscription_report_id' => 49, 'bank' => 'BCP', 'status' => 'CPP', 'currency' => 'PEN', 'amount' => 18000.00, 'expiration_days' => 28],
            ['subscription_report_id' => 50, 'bank' => 'Interbank', 'status' => 'DEF', 'currency' => 'PEN', 'amount' => 25500.00, 'expiration_days' => 42],
            ['subscription_report_id' => 51, 'bank' => 'BBVA', 'status' => 'NOR', 'currency' => 'PEN', 'amount' => 7800.00, 'expiration_days' => 0],
            ['subscription_report_id' => 51, 'bank' => 'BanBif', 'status' => 'NOR', 'currency' => 'PEN', 'amount' => 11200.00, 'expiration_days' => 0],
            ['subscription_report_id' => 52, 'bank' => 'Scotiabank', 'status' => 'CPP', 'currency' => 'PEN', 'amount' => 16500.00, 'expiration_days' => 18],
            ['subscription_report_id' => 53, 'bank' => 'BCP', 'status' => 'PER', 'currency' => 'PEN', 'amount' => 41000.00, 'expiration_days' => 95],
            ['subscription_report_id' => 54, 'bank' => 'Interbank', 'status' => 'NOR', 'currency' => 'PEN', 'amount' => 8200.00, 'expiration_days' => 0],
            ['subscription_report_id' => 55, 'bank' => 'BBVA', 'status' => 'DEF', 'currency' => 'PEN', 'amount' => 29500.00, 'expiration_days' => 55],
            ['subscription_report_id' => 55, 'bank' => 'BanBif', 'status' => 'CPP', 'currency' => 'PEN', 'amount' => 12800.00, 'expiration_days' => 25],
            ['subscription_report_id' => 56, 'bank' => 'Scotiabank', 'status' => 'NOR', 'currency' => 'PEN', 'amount' => 6500.00, 'expiration_days' => 0],
            ['subscription_report_id' => 57, 'bank' => 'BCP', 'status' => 'NOR', 'currency' => 'PEN', 'amount' => 10200.00, 'expiration_days' => 0],
            ['subscription_report_id' => 57, 'bank' => 'Interbank', 'status' => 'CPP', 'currency' => 'PEN', 'amount' => 23500.00, 'expiration_days' => 30],
            ['subscription_report_id' => 58, 'bank' => 'BBVA', 'status' => 'NOR', 'currency' => 'PEN', 'amount' => 9500.00, 'expiration_days' => 0],
            ['subscription_report_id' => 59, 'bank' => 'BanBif', 'status' => 'DEF', 'currency' => 'PEN', 'amount' => 34000.00, 'expiration_days' => 50],
            ['subscription_report_id' => 60, 'bank' => 'Scotiabank', 'status' => 'NOR', 'currency' => 'PEN', 'amount' => 7200.00, 'expiration_days' => 0],
            ['subscription_report_id' => 60, 'bank' => 'BCP', 'status' => 'PER', 'currency' => 'PEN', 'amount' => 46000.00, 'expiration_days' => 82],
            ['subscription_report_id' => 61, 'bank' => 'Interbank', 'status' => 'CPP', 'currency' => 'PEN', 'amount' => 15800.00, 'expiration_days' => 22],
            ['subscription_report_id' => 62, 'bank' => 'BBVA', 'status' => 'NOR', 'currency' => 'PEN', 'amount' => 8800.00, 'expiration_days' => 0],
            ['subscription_report_id' => 63, 'bank' => 'BanBif', 'status' => 'NOR', 'currency' => 'PEN', 'amount' => 12000.00, 'expiration_days' => 0],
            ['subscription_report_id' => 63, 'bank' => 'Scotiabank', 'status' => 'DEF', 'currency' => 'PEN', 'amount' => 27500.00, 'expiration_days' => 45],
            ['subscription_report_id' => 64, 'bank' => 'BCP', 'status' => 'CPP', 'currency' => 'PEN', 'amount' => 19000.00, 'expiration_days' => 28],
            ['subscription_report_id' => 65, 'bank' => 'Interbank', 'status' => 'NOR', 'currency' => 'PEN', 'amount' => 6800.00, 'expiration_days' => 0],
            ['subscription_report_id' => 66, 'bank' => 'BBVA', 'status' => 'PER', 'currency' => 'PEN', 'amount' => 43000.00, 'expiration_days' => 90],
            ['subscription_report_id' => 67, 'bank' => 'BanBif', 'status' => 'NOR', 'currency' => 'PEN', 'amount' => 10500.00, 'expiration_days' => 0],
            ['subscription_report_id' => 67, 'bank' => 'Scotiabank', 'status' => 'CPP', 'currency' => 'PEN', 'amount' => 21000.00, 'expiration_days' => 18],
            ['subscription_report_id' => 68, 'bank' => 'BCP', 'status' => 'DEF', 'currency' => 'PEN', 'amount' => 16000.00, 'expiration_days' => 40],
            ['subscription_report_id' => 69, 'bank' => 'Interbank', 'status' => 'NOR', 'currency' => 'PEN', 'amount' => 9000.00, 'expiration_days' => 0],
            ['subscription_report_id' => 70, 'bank' => 'BBVA', 'status' => 'NOR', 'currency' => 'PEN', 'amount' => 7500.00, 'expiration_days' => 0],
            ['subscription_report_id' => 70, 'bank' => 'BanBif', 'status' => 'CPP', 'currency' => 'PEN', 'amount' => 24500.00, 'expiration_days' => 25],
            ['subscription_report_id' => 71, 'bank' => 'Scotiabank', 'status' => 'PER', 'currency' => 'PEN', 'amount' => 38500.00, 'expiration_days' => 78],
            ['subscription_report_id' => 72, 'bank' => 'BCP', 'status' => 'NOR', 'currency' => 'PEN', 'amount' => 11500.00, 'expiration_days' => 0],
            ['subscription_report_id' => 73, 'bank' => 'Interbank', 'status' => 'DEF', 'currency' => 'PEN', 'amount' => 30000.00, 'expiration_days' => 52],
            ['subscription_report_id' => 74, 'bank' => 'BBVA', 'status' => 'NOR', 'currency' => 'PEN', 'amount' => 8500.00, 'expiration_days' => 0],
            ['subscription_report_id' => 74, 'bank' => 'BanBif', 'status' => 'CPP', 'currency' => 'PEN', 'amount' => 17000.00, 'expiration_days' => 20],
            ['subscription_report_id' => 75, 'bank' => 'Scotiabank', 'status' => 'NOR', 'currency' => 'PEN', 'amount' => 6200.00, 'expiration_days' => 0],
            ['subscription_report_id' => 76, 'bank' => 'BCP', 'status' => 'NOR', 'currency' => 'PEN', 'amount' => 13800.00, 'expiration_days' => 0],
            ['subscription_report_id' => 76, 'bank' => 'Interbank', 'status' => 'DEF', 'currency' => 'PEN', 'amount' => 26000.00, 'expiration_days' => 48],
            ['subscription_report_id' => 77, 'bank' => 'BBVA', 'status' => 'CPP', 'currency' => 'PEN', 'amount' => 14500.00, 'expiration_days' => 15],
            ['subscription_report_id' => 78, 'bank' => 'BanBif', 'status' => 'PER', 'currency' => 'PEN', 'amount' => 40000.00, 'expiration_days' => 85],
            ['subscription_report_id' => 79, 'bank' => 'Scotiabank', 'status' => 'NOR', 'currency' => 'PEN', 'amount' => 9800.00, 'expiration_days' => 0],
            ['subscription_report_id' => 80, 'bank' => 'BCP', 'status' => 'NOR', 'currency' => 'PEN', 'amount' => 7000.00, 'expiration_days' => 0],
            ['subscription_report_id' => 80, 'bank' => 'Interbank', 'status' => 'CPP', 'currency' => 'PEN', 'amount' => 22000.00, 'expiration_days' => 28],
            ['subscription_report_id' => 81, 'bank' => 'BBVA', 'status' => 'DEF', 'currency' => 'PEN', 'amount' => 18500.00, 'expiration_days' => 42],
            ['subscription_report_id' => 82, 'bank' => 'BanBif', 'status' => 'NOR', 'currency' => 'PEN', 'amount' => 10800.00, 'expiration_days' => 0],
            ['subscription_report_id' => 83, 'bank' => 'Scotiabank', 'status' => 'NOR', 'currency' => 'PEN', 'amount' => 8200.00, 'expiration_days' => 0],
            ['subscription_report_id' => 83, 'bank' => 'BCP', 'status' => 'PER', 'currency' => 'PEN', 'amount' => 45000.00, 'expiration_days' => 92],
            ['subscription_report_id' => 84, 'bank' => 'Interbank', 'status' => 'CPP', 'currency' => 'PEN', 'amount' => 16500.00, 'expiration_days' => 22],
            ['subscription_report_id' => 85, 'bank' => 'BBVA', 'status' => 'NOR', 'currency' => 'PEN', 'amount' => 12500.00, 'expiration_days' => 0],
            ['subscription_report_id' => 86, 'bank' => 'BanBif', 'status' => 'DEF', 'currency' => 'PEN', 'amount' => 32000.00, 'expiration_days' => 55],
            ['subscription_report_id' => 87, 'bank' => 'Scotiabank', 'status' => 'NOR', 'currency' => 'PEN', 'amount' => 7800.00, 'expiration_days' => 0],
            ['subscription_report_id' => 87, 'bank' => 'BCP', 'status' => 'CPP', 'currency' => 'PEN', 'amount' => 20500.00, 'expiration_days' => 25],
            ['subscription_report_id' => 88, 'bank' => 'Interbank', 'status' => 'NOR', 'currency' => 'PEN', 'amount' => 9500.00, 'expiration_days' => 0],
            ['subscription_report_id' => 89, 'bank' => 'BBVA', 'status' => 'PER', 'currency' => 'PEN', 'amount' => 37000.00, 'expiration_days' => 80],
            ['subscription_report_id' => 90, 'bank' => 'BanBif', 'status' => 'NOR', 'currency' => 'PEN', 'amount' => 6500.00, 'expiration_days' => 0],
            ['subscription_report_id' => 90, 'bank' => 'Scotiabank', 'status' => 'CPP', 'currency' => 'PEN', 'amount' => 23000.00, 'expiration_days' => 30],
            ['subscription_report_id' => 91, 'bank' => 'BCP', 'status' => 'DEF', 'currency' => 'PEN', 'amount' => 15500.00, 'expiration_days' => 45],
            ['subscription_report_id' => 92, 'bank' => 'Interbank', 'status' => 'NOR', 'currency' => 'PEN', 'amount' => 11000.00, 'expiration_days' => 0],
            ['subscription_report_id' => 93, 'bank' => 'BBVA', 'status' => 'NOR', 'currency' => 'PEN', 'amount' => 8000.00, 'expiration_days' => 0],
            ['subscription_report_id' => 93, 'bank' => 'BanBif', 'status' => 'CPP', 'currency' => 'PEN', 'amount' => 19500.00, 'expiration_days' => 18],
            ['subscription_report_id' => 94, 'bank' => 'Scotiabank', 'status' => 'PER', 'currency' => 'PEN', 'amount' => 42500.00, 'expiration_days' => 88],
            ['subscription_report_id' => 95, 'bank' => 'BCP', 'status' => 'NOR', 'currency' => 'PEN', 'amount' => 10200.00, 'expiration_days' => 0],
            ['subscription_report_id' => 96, 'bank' => 'Interbank', 'status' => 'DEF', 'currency' => 'PEN', 'amount' => 28000.00, 'expiration_days' => 50],
            ['subscription_report_id' => 97, 'bank' => 'BBVA', 'status' => 'NOR', 'currency' => 'PEN', 'amount' => 7200.00, 'expiration_days' => 0],
            ['subscription_report_id' => 97, 'bank' => 'BanBif', 'status' => 'CPP', 'currency' => 'PEN', 'amount' => 21500.00, 'expiration_days' => 22],
            ['subscription_report_id' => 98, 'bank' => 'Scotiabank', 'status' => 'NOR', 'currency' => 'PEN', 'amount' => 13000.00, 'expiration_days' => 0],
            ['subscription_report_id' => 99, 'bank' => 'BCP', 'status' => 'NOR', 'currency' => 'PEN', 'amount' => 9800.00, 'expiration_days' => 0],
            ['subscription_report_id' => 99, 'bank' => 'Interbank', 'status' => 'DEF', 'currency' => 'PEN', 'amount' => 35000.00, 'expiration_days' => 48],
            ['subscription_report_id' => 100, 'bank' => 'BBVA', 'status' => 'CPP', 'currency' => 'PEN', 'amount' => 17500.00, 'expiration_days' => 28],
        ];

        DB::table('report_loans')->insert($loans);
    }
}
